### PR TITLE
[Fix] Fix red arrow

### PR DESCRIPTION
**Pull request by zerodegress**
Simply remove["<", ">"] from language-configuration.json to fix it.
I think it should be safe.

### CODE REVIEW

**Comment by zerodegress** [comment]
#20

**Comment by HactarCE** [comment]
@PolyMeilex Please merge this. It's a trivial change that fixes a glaring bug.

**Comment by PolyMeilex** [comment]
This is a hack that will break closing bracket highlighting on hover, but sure I don't have any better ideas anyway.

**Comment by PolyMeilex** [comment]
@zerodegress Thanks!

**Pull request merged**
